language: node_js
node_js:
- '9'
before_install:
- npm i -g npm@6.0.1
before_script:
- npm install
- rm -rf ./server/routes
- mkdir ./server/routes
- "./node_modules/.bin/tsoa routes"
- "./node_modules/.bin/tsc -p tsconfig.json --module commonjs --sourceMap --target
  ES5"
- yarn global add nyc
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- nyc --reporter=lcov yarn run test
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
env:
  matrix:
  - port=3000 secret=test-environment-secret expiry=2 DB_TEST_ADDRESS=ds233970.mlab.com:33970 DB_TEST=qnapusatest
  global:
  - CC_TEST_REPORTER_ID=742205729651651616ea73723112f1ea84b253ced03739b10fa6ad3ca4187e7c
  - secure: BdbMd7znm4qj1KSYQguasYEUc9IMhWGH7E16isyKfyWdaIh6gKlnbxRC7Ac+MuXNSsUEoxgI1QahJ7/vhTXjUQhhn+vtj/1bbt5zLxA7FVrQH6p3C5cIbZTPEWiKCu4rBK7PwQ7hLKJI5eYSJ2sdFHosMt9wojj0IazMGEeqz7szIRNYtWtMoD28tFFbpxomPQEpF5Cqb0xC7QQ58AsSUKg3tZ2Nt/yf0mItLpfziBHreEr42UuD7DAF2yNQzRazNCcZR2ns4JZyPrQWcAkQrXrKU+5yloQSWN5gQ63gAYA92vUvteRMR6pM8nOrkruDk59ezY029wjKl1tsT2CMgZkjAPYM7SwXbUvorVubysTCxc6UHFHEQXJBev7CNi1h4KRJ0HmwQpbvy1y7dcrQGqgT2qrtBYGIqBGPZTfr+cAIGS/tlp4VG2+u3EBAObRD0+mLrBQ63BF8FV0VzgEVhE96Prrb6wHr+eV7s1kqckw0hDHc1sxPI31N5VwQkaKYUD0jPBp7vK0UmcNGXG/WGA11OXOQCF5ZC3DsMvdII9AZWxjTGX8dUM7a5/UCJrH6N40Ilyl7Mplw16pQzIrr2+ZEeqeldEohT815jgj7iTGGnHUpUmIv2dMgtJzpoLXVg8rFukWJ6x3WUlvGosIS7pEalg6QWQoatffUG4ucpfQ=
  - secure: eRzE8Rk5o+ja/kg+nwxAU2DaV3mCQAwVwngWqq6U8FhiJ0TKFAOBGLkBpGsoYfy5tcs5bPHYQtXVaJBrNJAUbUl3WVBonRf+oLzMqFNscC6YTp3AvzEhok6Laix3CT4ZsJYlXyLpRJHykwwqrCEtar31dfCRXEM/IOosfDOAkNP1529p45yQiA6w///U3CZGiTplMKv0rxDwafv9j8Ivq35ZgJm6G68Cb8OSJ8UqgilekrjjwZRH498rHJmxe7udjgVp9Jz3riZ95ZykLRpr87rwMwE3MBb+3bUXjW15/ZDOa7VImt7rGraMw1RT984DgU6F4IPj94cdyEGyORBrxZbbBwCtHqf0GDZQSOIqL8dGNz7cUK4qc/yhhDxjxQbHTVDozlGsWhYl25Azk1hH82L8NlaVXdLJiK53D4GCePehlC3o0z0gxK8MMzRAqyMcfh7jHp7SezUgCceoFhd8kt0idg8JZ6to2X+pQ/RHBbE+s1KhU8DjoCF7+7lCrBIgPL0UPCMBKieu2rapZJc8Scf3TUJ7sUhomVB339gG9mznwANllWwqrZbgEZ7vbMxvZ+/BJp8NBSRQDOXGdHlA2Z/xi+uIXLC/RLjdvDh9wY4et8PEu41Zuwac4Q8CMYNnX1dKregRNr7BBEoPai6dB9xvtleeJf+xrHb2l8jynyw=
  - secure: nqNye2e0GBAWmOuRdFUbhIdBrs2GpmyELjll1n4IbIx/otDLkhNctbdxweAmGaXcsQf84PPXT2oo8KFO1ARi42ywHkLfKdhHqpV/K3ckkK1A9nF/UbOxGklk2tmX9nbPM+SrIEGjY6tJt9p6XRNvZFuOFfhz6tADTKXsY+aGbwTNZVRll+HU8l4lyzPQoGgoeHfdRT5SXBUeosde8MmH65fybjO6nX9Yli/q03ZS+GQhjOFR943NF7u2RtdMfae8mjOrxlv5W8XybTCRgmru3pTWAfToINqKyJsAG+IqA3aaBD8aB+MIimSlokq8glSUEG/3iUbTDcGiGV6n5jg8bTOl5jijx1pi1EA+ltkXaVgCQzE/PMN7MuHEyWtYBA2TTYBn09RK02Y/duLpfA6VPZo6hBe2tCz8vUCOB9pFvwD1qlQqDby5bvHczdnqd1Y2I1mvi2DjKT6HJdfBKYrFn+985TaJeuBDZTdvPCxAo2Ei4k4lMNWj5HniT/aD4dKCID31q5DdWx4yyYy5qGouRq3dmAxQts9UsLOIU2Guu4N5sMJKkufmVf4mwtMp2s73f5UJ3+xXovZhTzSTgReQJZTEYVJlKnF3o4SxmWC581znW3T07Ln6F/U2ISaTnys04vzFvS23eGNvzDtLs3p14m/fpo4QZWc/g8TiqeI/2dA=
